#!/usr/bin/python2
#########{colors}################
basic_green 	=	"\033[0;32m"#
green			=	"\033[1;32m"#
green_underline	=	"\033[4;32m"#
basic_yellow	=	"\033[0;33m"#
yellow 			=	"\033[1;33m"#
white			=	"\033[0;37m"#
whiteb			=	"\033[1;37m"#
basic_red		=	"\033[0;31m"#
red				=	"\033[1;31m"#
cyan			=	"\033[1;36m"#
basic_cyan		=	"\033[0;36m"#
blue			=	"\033[1;34m"#
basic_blue		=	"\033[0;34m"#
light_blue		=	"\033[0;94m"#
blue_underline	=	"\033[4;34m"#
default			=	"\033[0m"   #
underline		=	"\033[4;32m"#
r               =   "\033[1;31m"#
g               =   "\033[1;32m"#
y               =   "\033[1;33m"#
b               =   "\033[1;34m"#
c               =   "\033[1;36m"#
#################################
from optparse import OptionParser
from optparse import OptionGroup
import requests
import time
import shodan
import os
import sys
from bs4 import BeautifulSoup
from urllib2 import *
import urllib
parser = OptionParser("modules auxiliary")
parser.add_option("-a", "--auxiliary", dest="auxiliary", help=" input module auxiliary ")
group1 = OptionGroup(parser, "ip_number_information","""ex:{ wafauxiliary -a ip_number_information }""")
group1.add_option("-i", "--ip",dest="ip",help=" create nember ",default="help")
parser.add_option_group(group1)
group2 = OptionGroup(parser, "admin_panel_findler","""ex:{ wafauxiliary -a create_fake_nember }""")
group2.add_option("-u", "--url",dest="url",help=" create nember ",default="help")
parser.add_option_group(group2)
group3 = OptionGroup(parser, "gather_shodan_search ","""ex:{ wafauxiliary -a create_fake_nember }""")
group3.add_option("-k", "--apikey",dest="apikey",help=" create nember ",default="help")
group3.add_option("-s", "--search",dest="search",help=" create nember ",default="help")
parser.add_option_group(group3)
(options, args) = parser.parse_args()
auxiliary = options.auxiliary
if auxiliary == "ip_number_information":
  ip  = options.ip
  if ip == "help":
      print ""
      print"  help:"
      print"      wafauxiliary -a ip_number_information -i {input ip target }"
      print"      exmples:"
      print"             wafauxiliary -a ip_number_information -i 192.168.1.1 "
  else :
   print ''
   time.sleep(0.01)
   print light_blue +'[...] Searching for ' + basic_yellow + ip
   print ''
   request = requests.get('http://ip-api.com/json/'+ip)
   data = request.json()
   print green + 'Advanced Information'
   print basic_green + 'Lat           :      ' + white + str(data['lat'])
   print basic_green + 'Lon           :      ' + white + str(data['lon'])
   print basic_green + 'Coord         :      ' + white + str(data['lat']) + ',' + str(data['lon'])
   print basic_green + 'Google Maps   :      ' + white + 'https://www.google.com.br/maps/place/' + str(data['lat']) + ',' + str(data['lon'])
   print ''
   print green + 'Basic Information'
   print basic_green + 'Country       :      ' + white + data['country'] + '[' + data['countryCode'] + ']'
   print basic_green + 'City          :      ' + white + data['city'] + ' - ' + data['region'] + ' - {' + data['regionName'] + '}'
   print basic_green + 'Timezone      :      ' + white + data['timezone']
   print basic_green + 'Zip           :      ' + white + data['zip']
   print ''
   print green + 'Internet Information'
   print basic_green + 'ISP           :      ' + white + data['isp']
   print basic_green + 'Org           :      ' + white + data['as']
   print ''
   time.sleep(2)
   print basic_yellow + '[*] Done '
   print ''
elif auxiliary == "admin_panel_findler":
 url = str(options.url)
 if url == "help":
        print ""
        print"  help:"
        print"      wafauxiliary -a admin_panel_findler -u { url target }"
        print"      exmples:"
        print"             wafauxiliary -a admin_panel_findler -u google.com "
 else:
    f = open("core/link.txt","r");
    link = url
    print blue+"[*]"+default+"starting the scanning"
    print "\n\nAvilable links : \n"
    while True:
      sub_link = f.readline()
      if not sub_link:
         break
      req_link = "http://"+link+"/"+sub_link
      req = Request(req_link)
      try:
         response = urlopen(req)
      except HTTPError as e:
        continue
      except URLError as e:
        continue
      else:
        print "OK => ",req_link
elif auxiliary == "gather_shodan_search":
 apikey = str(options.apikey)
 search = str(options.search)
 if apikey == "help" or search =="help":
        print ""
        print"  help:"
        print"      wafauxiliary -a gather_shodan_search -k { apikey } -s { search }"
        print"      exmples:"
        print"             wafauxiliary -a gather_shodan_search -k ghhftyhbgygfdfgh.... -s webcam "
 else:
    def shodan_search(search, apikey):
     if apikey:
        API_KEY = apikey
     else:
        API_KEY = red+'[-]'+default+'REPLACE WITH API KEY AND KEEP QUOTES'

     api = shodan.Shodan(API_KEY)
     ips_and_ports = []

    # Get IPs from Shodan search results
     try:
        results = api.search(search, page=1)
        total_results = results['total']
        print blue+'[*]'+default+'Total results: {0}'.format(total_results)
        print blue+'[*]'+default+'First page:'
        for r in results['matches']:
            ip = r['ip_str']
            port = r['port']
            ip_port = '{0}:{1}'.format(ip, port)
            print green+' [+]'+default, ip_port

     except Exception as e:
        print red+'[-]'+default+'Shodan search error:', e
    shodan_search(search, apikey)
elif auxiliary == "show_auxiliary":
    print ""
    print "auxiliary "
    print "==========   "
    print "   #      Name                                          Description"
    print "   -      ----                                          -----------"
    print "   01     ip_number_information                         Collection of IP information"
    print "   02     admin_panel_findler                           Admin panel"
    print "   03     gather_shodan_search                          Shodan Search"
    print ""
else:
    print"""     

    write [ wafauxiliary-h  : help ]
    write [ wafauxiliary -a show_auxiliary :  show modules auxiliary ]
    write [ wafauxiliary -a {modules} .... ]

        exmples :
            wafauxiliary -a show_auxiliary
            wafauxiliary -a ip_number_information 
            wafauxiliary -a admin_panel_findler
            wafauxiliary -a gather_shodan_search
"""