#!/usr/bin/python2
#########{colors}################
basic_green 	=	"\033[0;32m"#
green			=	"\033[1;32m"#
green_underline	=	"\033[4;32m"#
basic_yellow	=	"\033[0;33m"#
yellow 			=	"\033[1;33m"#
white			=	"\033[0;37m"#
whiteb			=	"\033[1;37m"#
basic_red		=	"\033[0;31m"#
red				=	"\033[1;31m"#
cyan			=	"\033[1;36m"#
basic_cyan		=	"\033[0;36m"#
blue			=	"\033[1;34m"#
basic_blue		=	"\033[0;34m"#
light_blue		=	"\033[0;94m"#
blue_underline	=	"\033[4;34m"#
default			=	"\033[0m"   #
underline		=	"\033[4;32m"#
r               =   "\033[1;31m"#
g               =   "\033[1;32m"#
y               =   "\033[1;33m"#
b               =   "\033[1;34m"#
c               =   "\033[1;36m"#
#################################
from optparse import OptionParser
from optparse import OptionGroup
import requests
from bs4 import BeautifulSoup
parser = OptionParser("modules Spam")

parser.add_option("-s", "--spam", dest="spam", help=" input module spam ")
group = OptionGroup(parser, "create_fake_nember","""
creating nember of nember_list
 ex:{ wafspam -s create_fake_nember  }                                                
                                                    """)
group.add_option("-n", "--nember",dest="nember",help=" create nember ",default="help")
parser.add_option_group(group)

(options, args) = parser.parse_args()
spam = options.spam


if spam == "create_fake_nember":
 nember = options.nember
 if nember == "help":
     print ""
     print"  help:"
     print"      wafspam -s create_fake_nember -n nember_list : print nember list"
     print"      wafspam -s create_fake_nember -n {nember with nember_list}"
     print"        exmples:"
     print"               wafspam -s create_fake_nember -n 447537150994 "
 elif nember == "nember_list":
     print blue + "[*]" + default + "starting scan your nember"
     url_fake = "http://receivefreesms.net/"
     face_mail = requests.get(url_fake, headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"})
     soup = BeautifulSoup(face_mail.content, "html.parser")
     print green + "[+]" + default + 'Available numbers'
     for div in soup.find_all("div", {"class": "cuadro"}):
         nm = div.a.text.strip('+')
         print green + "[+]" + default + "the nember is : " + nm
 else:
     print blue + "[*]" + default + "creating your nember "
     while True:
         url = "http://receivefreesms.net/free-sms-" + str(nember) + ".html"
         re = requests.get(url, headers={
             "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"})
         soup2 = BeautifulSoup(re.content, "html.parser")

         fr = soup2.find("td", {"data-title": "From Number"})
         from_nember = fr.text.strip(
             'if(location.href.indexOf("receivefreesms")<=0){ alert("STOP stealing my numbers!"); document.location="http://receivefreesms.net/"; }')

         ti = soup2.find("td", {"data-title": "Time"})
         time = ti.text
         mess = soup2.find("td", {"data-title": "Message"})
         message = mess.text
         print " ____________________________________________________________________________________________"
         print "|   set nember     |  +" + str(nember) + "                                                          |"
         print "|__________________|_________________________________________________________________________|"
         print "|   From Number    |  " + from_nember + "                                                            |"
         print "|__________________|_________________________________________________________________________|"
         print "|      Time        |  " + time + "                                                         |"
         print "|__________________|_________________________________________________________________________|"
         print "|    Message       |  " + message + "                       |"
         print "|__________________|_________________________________________________________________________|"
         raw_input('')
         print blue + "[*]" + default + "refrushe"

elif spam == "show_spam":
    print ""
    print "spam"
    print "====="
    print "   #      Name                                          Description"
    print "   -      ----                                          -----------"
    print "   01     create_fake_nember                            Make a phone number"
    print ""
else:
 print"""     
    
    write [ wafspam -h  : help ]
    write [ wafspam -s show_spam :  show modules spam ]
    write [ wafspam -s {modules} .... ]
    
        exmples :
            wafspam -s show_spam
            wafspam -s create_fake_nember 
 """